### ISSUE TITLE
Single sequential execution reports error

### ISSUE THREAD

**Issue by freemo** [Syncleus/aparapi#23]
_From @dlippold on November 21, 2016 17:1_

When I execute the example "add" (on Linux with JDK 7) in the single sequential Java loop, set by the property "-Dcom.amd.aparapi.executionMode=SEQ", I get the following error message:

> Exception in thread "main" java.lang.IllegalStateException: Can't run range with group size >1 sequentially. Barriers would deadlock!
> 	at com.amd.aparapi.internal.kernel.KernelRunner.executeJava(KernelRunner.java:242)
> 	at com.amd.aparapi.internal.kernel.KernelRunner.execute(KernelRunner.java:1196)
> 	at com.amd.aparapi.Kernel.execute(Kernel.java:2028)
> 	at com.amd.aparapi.Kernel.execute(Kernel.java:1962)
> 	at com.amd.aparapi.Kernel.execute(Kernel.java:1933)
> 	at com.amd.aparapi.sample.add.Main.main(Main.java:67)

Steps to reproduce on Linux:

1. "java -version" gives "OpenJDK Runtime Environment (IcedTea 2.6.7) (7u111-2.6.7-2~deb7u1)
OpenJDK 64-Bit Server VM (build 24.111-b01, mixed mode)"
2. mkdir Aparapi
3. cd Aparapi
4. unzip ~/dist_linux_x86_64.zip
5. cd samples/add/
6. java -Djava.library.path=../..  -classpath ../../aparapi.jar:add.jar -Dcom.amd.aparapi.executionMode=SEQ com.amd.aparapi.sample.add.Main

_Copied from original issue: aparapi/aparapi#43_

**Comment by freemo** [comment]
_From @SubaruWRC on November 21, 2016 17:22_

I believe that is the correct behavior with SEQ mode. Does the example work correctly in JTP mode?
