### ISSUE TITLE
Calling createProgram results in exception

### ISSUE THREAD

**Issue by freemo** [Syncleus/aparapi#30]
Anytime createProgram is called an exception is thrown due to improper linking.

```java

java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:294)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.UnsatisfiedLinkError: com.aparapi.internal.jni.OpenCLJNI.createProgram(Lcom/aparapi/device/OpenCLDevice;Ljava/lang/String;)Lcom/aparapi/internal/opencl/OpenCLProgram;
        at com.aparapi.internal.jni.OpenCLJNI.createProgram(Native Method)
        at com.aparapi.internal.opencl.OpenCLProgram.createProgram(OpenCLProgram.java:76)
        at com.aparapi.device.OpenCLDevice.bind(OpenCLDevice.java:423)
        at com.aparapi.device.OpenCLDevice.bind(OpenCLDevice.java:351)
        at com.aparapi.examples.extension.FFTExample.main(FFTExample.java:112)
        at com.aparapi.examples.All.selected(All.java:142)
        at com.aparapi.examples.All.main(All.java:79)
        ... 6 more
```

This is related to this issue: https://github.com/Syncleus/aparapi-examples/issues/3

**Comment by freemo** [comment]
After fixing the last bug a new one came up where kernel = null. For this reason it seems the binaryKey specific code was never properly tested. This means we can abandon this on the 2.x branch and instead use the method proposed by ucores, which supposidly is tested a bit better and actually works.

**Comment by freemo** [comment]
this is working now on linux and osx, just need to compile it for windows.

**Comment by freemo** [comment]
Update: So got the ucores code in and its working great. Recompiled the native library for linux and osx and it passes all tests. Just need to compile it for windows and test it and then ill be able to close this ticket.
