### ISSUE TITLE
Exception thrown when running on Windows.

### ISSUE THREAD

**Issue by freemo** [Syncleus/aparapi#37]
The following exception occurs when trying to run Aparapi on windows. The exception never seems to occur on linux or mac.

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\Vincenzo\AppData\Local\Temp\libaparapi_x86_643218484219112159561.dll: Can't find dependent libraries
at java.lang.ClassLoader$NativeLibrary.load(Native Method)
at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
at java.lang.Runtime.load0(Runtime.java:809)
at java.lang.System.load(System.java:1086)
at com.aparapi.natives.util.NativeUtils.loadLibraryFromJar(NativeUtils.java:100)
at com.aparapi.natives.NativeLoader.load(NativeLoader.java:42)
at com.aparapi.internal.opencl.OpenCLLoader.<clinit>(OpenCLLoader.java:43)
at com.aparapi.internal.opencl.OpenCLPlatform.getOpenCLPlatforms(OpenCLPlatform.java:73)
at com.aparapi.device.OpenCLDevice.listDevices(OpenCLDevice.java:458)
at com.aparapi.internal.kernel.KernelManager.createDefaultPreferredDevices(KernelManager.java:203)
at com.aparapi.internal.kernel.KernelManager.createDefaultPreferences(KernelManager.java:178)
at com.aparapi.internal.kernel.KernelManager.<init>(KernelManager.java:46)
at com.aparapi.internal.kernel.KernelManager.<clinit>(KernelManager.java:38)
at com.aparapi.internal.kernel.KernelRunner.<init>(KernelRunner.java:170)
at com.aparapi.Kernel.prepareKernelRunner(Kernel.java:2270)
at com.aparapi.Kernel.execute(Kernel.java:2439)
at com.aparapi.Kernel.execute(Kernel.java:2396)
at com.aparapi.Kernel.execute(Kernel.java:2371)
```

**Comment by freemo** [comment]
This bug has been fixed in release 1.3.4, which is now in maven central. So if anyone recently experienced problems running on windows please ensure you upgrade to this version, should fix the problem.

**Comment by AHoran** [comment]
I am getting this same issue on (some) windows machines.
I am using aparapi 1.3.4 and the aparapi-jni 1.1.2

I can compile and run my aparapi based app on my dev machines. However when i copy a compiled version to user machines then I get this problem.

**Comment by freemo** [comment]
Are the working machines all Mac and the machines that aren't Linux/Windows?

Mac comes with an open implementation preinstalled but on Windows and Linux
you have to install that yourself.

**Comment by AHoran** [comment]
No, the working machines are windows, and the non-working machines are windows.

As far as I can tell all the machines have a working OpenCL runtime. Do I need an OpenCL SDK on every machine that will run my application?

**Comment by AHoran** [comment]
When I install the _Intel SDK for OpenCL Applications_ then the application will run...

I wasn't expecting to need the SDK at runtime, as my app is distributed to normal users, and there's no way I can request or expect that they'll have an operational OpenCL SDK on their machines.

**Comment by AHoran** [comment]
This is my stacktrace.

Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\adam.horan\AppData\Local\Temp\libaparapi_x86_64111971314637878404.dll: Can't find dependent libraries
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(Unknown Source)
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.load0(Unknown Source)
	at java.lang.System.load(Unknown Source)
	at com.aparapi.natives.util.NativeUtils.loadLibraryFromJar(NativeUtils.java:100)
	at com.aparapi.natives.NativeLoader.load(NativeLoader.java:42)
	at com.aparapi.internal.opencl.OpenCLLoader.<clinit>(OpenCLLoader.java:43)
	at com.aparapi.internal.opencl.OpenCLPlatform.getOpenCLPlatforms(OpenCLPlatform.java:73)
	at com.aparapi.device.OpenCLDevice.listDevices(OpenCLDevice.java:458)
	at com.aparapi.internal.kernel.KernelManager.createDefaultPreferredDevices(KernelManager.java:203)
	at com.aparapi.internal.kernel.KernelManager.createDefaultPreferences(KernelManager.java:178)
	at com.aparapi.internal.kernel.KernelManager.<init>(KernelManager.java:46)
	at com.aparapi.internal.kernel.KernelManager.<clinit>(KernelManager.java:38)
	at aparapitest.IntersectionFinder.findIntersections(IntersectionFinder.java:68)
	at aparapitest.AparapiTest.main(AparapiTest.java:47)

**Comment by freemo** [comment]
Unfortunately yes you need an open implementation which is a native library
installed. Not much way around that. I think calling it an sdk is a bit
misleading though as it's more like an API.

**Comment by freemo** [comment]
@AHoran did installing the opencl implementation (SDK) help? If so I'd like to close this ticket.

**Comment by freemo** [comment]
@AHoran  oops nevermind i noticed this issue has already been closed. BTW you are using the aparapi through maven and not directly right? You shouldnt be getting this error on the newer versions of aparapi if an opencl implementation is installed.

**Comment by freemo** [comment]
@AHoran  By the way I just checked here and it doesnt appear to require an SDK to run for me, but I did need to make sure opencl was installed. So I take back what I said earlier, you dont need the SDK installed to run the software.

**Comment by AHoran** [comment]
I am not using the maven POM, but i have retrieved the two latest jars/libraries from the maven site. In all of my error messages the long number in the .dll starts with _64 so i think i am trying to load up the correct dll.

On AMD based systems with latest Radeon drivers it always works. I have hit and miss results on Intel based systems with Intel graphics (ie laptops) and the standard Intel drivers. On the limited number of NVIDIA systems that I've tried, I'm having no success.

I am using GpuCapsViewer to test if i have a working OpenCL platform available. In this tool you can navigate to the demos tab and run OpenCL based tests. These work on my Nvidia system, see screenshot from the NVIDIA machine.

![image](https://user-images.githubusercontent.com/3496701/27116377-417e3cc4-5114-11e7-94e0-96f97b46c847.png)

If I install the Intel SDK or the AMD SDK then it works. However I had understood that the full SDK was not necessary and the OpenCL runtime/drivers was sufficient. (The various docs are unclear). My application will be distributed to normal end-users and i don't want to have to describe to them how to find or install the various SDKs

Should we move this to a new issue? I initially thought this was related to the closed issue.

**Comment by AHoran** [comment]
I can also download and execute samples from NVidia from this page https://developer.nvidia.com/opencl 

The first one _OpenCL Multi Threads_  gives me the following output:

> Detected 1 OpenCL devices of type CL_DEVICE_TYPE_GPU
> OpenCL Device #0 (Quadro K620), cl_device_id: 7711760
> clCreateProgramWithSource <kernel.cl> succeeded, program_length=87
> clBuildProgram <kernel.cl> succeeded
> clGetProgramBuildInfo returned: CL_SUCCESS
> 
> 
> Quadro K620: simpleIncrement(), cl_device_id: 7711760, event_id: 0
> Quadro K620: simpleIncrement(), cl_device_id: 7711760, event_id: 1
> Quadro K620: simpleIncrement(), cl_device_id: 7711760, event_id: 2
> Quadro K620: simpleIncrement(), cl_device_id: 7711760, event_id: 3
> Quadro K620: simpleIncrement(), cl_device_id: 7711760, event_id: 4
> Quadro K620: simpleIncrement(), cl_device_id: 7711760, event_id: 5
> Quadro K620: simpleIncrement(), cl_device_id: 7711760, event_id: 6
> Quadro K620: simpleIncrement(), cl_device_id: 7711760, event_id: 7
>

**Comment by freemo** [comment]
@AHoran yea lets move this to a new issue. I'm not exactly sure what the issue is but I will have to do some investigation for you.

**Comment by freemo** [comment]
@AHoran do the unit tests work for you at all?
