### ISSUE TITLE
declare helper method in Kernal that accept __private variable 

### ISSUE THREAD

**Issue by nejeoui** [Syncleus/aparapi#67]
i tried to define a helper method AddMod that accept __private byte Array but failed 
**1- the syntax** 
public  void addMod(final byte[] input1,final byte[] input2,final byte[] outputBytes,final int ID, byte[] PRIME_$private$32){

}

compile fine but calling the addMod with a __private variable PRIME throws runtime exception : 
<program source>:362:112: error: passing 'char *' to parameter of type '__global char *' changes address space of pointer
         net_spirea_oclGenerator_AdressKernel__addMod(this, this->input1, this->input2, this->outputBytes, ID, this->PRIME);
                                                                                                               ^~~~~~~~~~~
**2- the syntaxe** 
public  void addMod(final byte[] input1,final byte[] input2,final byte[] outputBytes,final int ID, @PrivateMemorySpace(value = 32) byte[] PRIME){

}

does not compile.

Any suggestions on how to declare a helper method with __private argument variable ?

thanks in advance.
A. Nejeoui

**Comment by freemo** [comment]
Yea you can find an example of it here:

https://github.com/shabanovd/aparapi/blob/9a8bd62bba2fade092452e5179cf697ed7aa38f0/src/test/java/com/aparapi/runtime/ArrayTest.java

I'm on my phone right now so can't view the full source code you posted.
Hope that helps, let me know if it doesnt.

**Comment by freemo** [comment]
@nejeoui Did that answer your question?

**Comment by nejeoui** [comment]
Hi freemo,
thank you for your quick reply.
the ArrayTest.java throw an exception at runtime 
i think the instruction int[] ints = new int[size]; inside the run method is causes the exception.

please find the full stack trace bellow : 
com.aparapi.internal.exception.ClassParseException: @7 NEWARRAY We don't support new instructions
	at com.aparapi.internal.model.MethodModel.createListOfInstructions(MethodModel.java:247)
	at com.aparapi.internal.model.MethodModel.init(MethodModel.java:1642)
	at com.aparapi.internal.model.MethodModel.<init>(MethodModel.java:1454)
	at com.aparapi.internal.model.ClassModel.computeMethodModel(ClassModel.java:2787)
	at com.aparapi.internal.model.ClassModel.access$1100(ClassModel.java:83)
	at com.aparapi.internal.model.ClassModel$5.compute(ClassModel.java:2764)
	at com.aparapi.internal.model.ClassModel$5.compute(ClassModel.java:2762)
	at com.aparapi.internal.model.ValueCache.computeIfAbsent(ValueCache.java:50)
	at com.aparapi.internal.model.ClassModel.getMethodModel(ClassModel.java:2778)
	at com.aparapi.internal.model.ClassModel.computeBasicEntrypoint(ClassModel.java:2841)
	at com.aparapi.internal.model.ClassModel$6.compute(ClassModel.java:2823)
	at com.aparapi.internal.model.ClassModel$6.compute(ClassModel.java:2821)
	at com.aparapi.internal.model.ValueCache.computeIfAbsent(ValueCache.java:50)
	at com.aparapi.internal.model.ClassModel.getEntrypoint(ClassModel.java:2831)
	at com.aparapi.internal.model.ClassModel.getEntrypoint(ClassModel.java:2850)
	at com.aparapi.internal.kernel.KernelRunner.executeInternalInner(KernelRunner.java:1272)
	at com.aparapi.internal.kernel.KernelRunner.executeInternalOuter(KernelRunner.java:1180)
	at com.aparapi.internal.kernel.KernelRunner.execute(KernelRunner.java:1170)
	at com.aparapi.Kernel.execute(Kernel.java:2473)
	at com.aparapi.Kernel.execute(Kernel.java:2430)
	at com.aparapi.Kernel.execute(Kernel.java:2405)
	at net.spirea.oclGenerator.test.ArrayTest$VectorKernel.test(ArrayTest.java:63)
	at net.spirea.oclGenerator.test.ArrayTest.test(ArrayTest.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:539)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:761)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:461)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:207)
Oct 22, 2017 9:58:37 AM com.aparapi.internal.kernel.KernelRunner fallBackToNextDevice
WARNING: Device failed for VectorKernel, devices={Apple<GPU>|Apple<CPU>|Java Alternative Algorithm|Java Thread Pool}: @7 NEWARRAY We don't support new instructions
com.aparapi.internal.exception.ClassParseException: @7 NEWARRAY We don't support new instructions
	at com.aparapi.internal.model.MethodModel.createListOfInstructions(MethodModel.java:247)
	at com.aparapi.internal.model.MethodModel.init(MethodModel.java:1642)
	at com.aparapi.internal.model.MethodModel.<init>(MethodModel.java:1454)
	at com.aparapi.internal.model.ClassModel.computeMethodModel(ClassModel.java:2787)
	at com.aparapi.internal.model.ClassModel.access$1100(ClassModel.java:83)
	at com.aparapi.internal.model.ClassModel$5.compute(ClassModel.java:2764)
	at com.aparapi.internal.model.ClassModel$5.compute(ClassModel.java:2762)
	at com.aparapi.internal.model.ValueCache.computeIfAbsent(ValueCache.java:50)
	at com.aparapi.internal.model.ClassModel.getMethodModel(ClassModel.java:2778)
	at com.aparapi.internal.model.ClassModel.computeBasicEntrypoint(ClassModel.java:2841)
	at com.aparapi.internal.model.ClassModel$6.compute(ClassModel.java:2823)
	at com.aparapi.internal.model.ClassModel$6.compute(ClassModel.java:2821)
	at com.aparapi.internal.model.ValueCache.computeIfAbsent(ValueCache.java:50)
	at com.aparapi.internal.model.ClassModel.getEntrypoint(ClassModel.java:2831)
	at com.aparapi.internal.model.ClassModel.getEntrypoint(ClassModel.java:2850)
	at com.aparapi.internal.kernel.KernelRunner.executeInternalInner(KernelRunner.java:1272)
	at com.aparapi.internal.kernel.KernelRunner.executeInternalOuter(KernelRunner.java:1180)
	at com.aparapi.internal.kernel.KernelRunner.execute(KernelRunner.java:1170)
	at com.aparapi.Kernel.execute(Kernel.java:2473)
	at com.aparapi.Kernel.execute(Kernel.java:2430)
	at com.aparapi.Kernel.execute(Kernel.java:2405)
	at net.spirea.oclGenerator.test.ArrayTest$VectorKernel.test(ArrayTest.java:63)
	at net.spirea.oclGenerator.test.ArrayTest.test(ArrayTest.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:539)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:761)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:461)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:207)
Oct 22, 2017 9:58:37 AM com.aparapi.internal.kernel.KernelRunner fallBackToNextDevice
WARNING: Trying next device: Apple<CPU>
com.aparapi.internal.exception.ClassParseException: @7 NEWARRAY We don't support new instructions
	at com.aparapi.internal.model.MethodModel.createListOfInstructions(MethodModel.java:247)
	at com.aparapi.internal.model.MethodModel.init(MethodModel.java:1642)
	at com.aparapi.internal.model.MethodModel.<init>(MethodModel.java:1454)
	at com.aparapi.internal.model.ClassModel.computeMethodModel(ClassModel.java:2787)
	at com.aparapi.internal.model.ClassModel.access$1100(ClassModel.java:83)
	at com.aparapi.internal.model.ClassModel$5.compute(ClassModel.java:2764)
	at com.aparapi.internal.model.ClassModel$5.compute(ClassModel.java:2762)
	at com.aparapi.internal.model.ValueCache.computeIfAbsent(ValueCache.java:50)
	at com.aparapi.internal.model.ClassModel.getMethodModel(ClassModel.java:2778)
	at com.aparapi.internal.model.ClassModel.computeBasicEntrypoint(ClassModel.java:2841)
	at com.aparapi.internal.model.ClassModel$6.compute(ClassModel.java:2823)
	at com.aparapi.internal.model.ClassModel$6.compute(ClassModel.java:2821)
	at com.aparapi.internal.model.ValueCache.computeIfAbsent(ValueCache.java:50)
	at com.aparapi.internal.model.ClassModel.getEntrypoint(ClassModel.java:2831)
	at com.aparapi.internal.model.ClassModel.getEntrypoint(ClassModel.java:2850)
	at com.aparapi.internal.kernel.KernelRunner.executeInternalInner(KernelRunner.java:1272)
	at com.aparapi.internal.kernel.KernelRunner.fallBackToNextDevice(KernelRunner.java:1154)
	at com.aparapi.internal.kernel.KernelRunner.fallBackToNextDevice(KernelRunner.java:1118)
	at com.aparapi.internal.kernel.KernelRunner.executeInternalInner(KernelRunner.java:1276)
	at com.aparapi.internal.kernel.KernelRunner.executeInternalOuter(KernelRunner.java:1180)
	at com.aparapi.internal.kernel.KernelRunner.execute(KernelRunner.java:1170)
	at com.aparapi.Kernel.execute(Kernel.java:2473)
	at com.aparapi.Kernel.execute(Kernel.java:2430)
	at com.aparapi.Kernel.execute(Kernel.java:2405)
	at net.spirea.oclGenerator.test.ArrayTest$VectorKernel.test(ArrayTest.java:63)
	at net.spirea.oclGenerator.test.ArrayTest.test(ArrayTest.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:539)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:761)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:461)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:207)
Oct 22, 2017 9:58:37 AM com.aparapi.internal.kernel.KernelRunner fallBackToNextDevice
WARNING: Device failed for VectorKernel, devices={Apple<CPU>|Java Alternative Algorithm|Java Thread Pool}: @7 NEWARRAY We don't support new instructions
com.aparapi.internal.exception.ClassParseException: @7 NEWARRAY We don't support new instructions
	at com.aparapi.internal.model.MethodModel.createListOfInstructions(MethodModel.java:247)
	at com.aparapi.internal.model.MethodModel.init(MethodModel.java:1642)
	at com.aparapi.internal.model.MethodModel.<init>(MethodModel.java:1454)
	at com.aparapi.internal.model.ClassModel.computeMethodModel(ClassModel.java:2787)
	at com.aparapi.internal.model.ClassModel.access$1100(ClassModel.java:83)
	at com.aparapi.internal.model.ClassModel$5.compute(ClassModel.java:2764)
	at com.aparapi.internal.model.ClassModel$5.compute(ClassModel.java:2762)
	at com.aparapi.internal.model.ValueCache.computeIfAbsent(ValueCache.java:50)
	at com.aparapi.internal.model.ClassModel.getMethodModel(ClassModel.java:2778)
	at com.aparapi.internal.model.ClassModel.computeBasicEntrypoint(ClassModel.java:2841)
	at com.aparapi.internal.model.ClassModel$6.compute(ClassModel.java:2823)
	at com.aparapi.internal.model.ClassModel$6.compute(ClassModel.java:2821)
	at com.aparapi.internal.model.ValueCache.computeIfAbsent(ValueCache.java:50)
	at com.aparapi.internal.model.ClassModel.getEntrypoint(ClassModel.java:2831)
	at com.aparapi.internal.model.ClassModel.getEntrypoint(ClassModel.java:2850)
	at com.aparapi.internal.kernel.KernelRunner.executeInternalInner(KernelRunner.java:1272)
	at com.aparapi.internal.kernel.KernelRunner.fallBackToNextDevice(KernelRunner.java:1154)
	at com.aparapi.internal.kernel.KernelRunner.fallBackToNextDevice(KernelRunner.java:1118)
	at com.aparapi.internal.kernel.KernelRunner.executeInternalInner(KernelRunner.java:1276)
	at com.aparapi.internal.kernel.KernelRunner.executeInternalOuter(KernelRunner.java:1180)
	at com.aparapi.internal.kernel.KernelRunner.execute(KernelRunner.java:1170)
	at com.aparapi.Kernel.execute(Kernel.java:2473)
	at com.aparapi.Kernel.execute(Kernel.java:2430)
	at com.aparapi.Kernel.execute(Kernel.java:2405)
	at net.spirea.oclGenerator.test.ArrayTest$VectorKernel.test(ArrayTest.java:63)
	at net.spirea.oclGenerator.test.ArrayTest.test(ArrayTest.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:539)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:761)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:461)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:207)
Oct 22, 2017 9:58:37 AM com.aparapi.internal.kernel.KernelRunner fallBackToNextDevice
WARNING: Trying next device: Java Alternative Algorithm

**Comment by freemo** [comment]
@nejeoui I think you need to pull down the latest version of master. This was just added to the code base yesterday. The test passes for me locally (on mac osx) and on our travis instance (linux). So should be working if your on the latest version of the master branch.

**Comment by nejeoui** [comment]
Thank you Jefferey for adding this valuable functionality to Aparapi.
i will pull down the latest version of master and give it a try. I'm working on an Aparapi based Multi Precision Arithmetics API that make a heavy use of _private memory space.

**Comment by freemo** [comment]
@nejeoui I didnt write the new functionality, it was @shabanovd. However the new functionality was to allow array creation inside a kernel. The functionality you actually are trying to use already existed from sometime back. It is just the unit test I showed you as an example is new as the unit test is intended to show array creation, it just happens to also use the same functionality you needed so i showed it to you as an example.

**Comment by freemo** [comment]
@nejeoui please let me know if this solves your question so i can close the ticket, or feel free to close the ticket yourself once you feel your question has been answered.

**Comment by nejeoui** [comment]
The code source from master branch compile fine. i can passe a _private array as argument using the syntaxe byte[] PRIME_$private$.
Thanks Aparapi Team.

**Comment by freemo** [comment]
Happy to help :)
